### ISSUE TITLE
Move to Ferrum + Cuprite for system tests.

### ISSUE THREAD

**Issue by existentialmutt** [bullet-train-co/bullet_train#141]
The default Selenium backend for system tests can be super flaky. Seems like every dev I've talked to has hit a frustrating experience with it. Usually the response is to give up on end to end tests and move on to more productive work.

Ferrum/Cuprite is a modern, pure Ruby alternative to Selenium that is faster and more reliable. Adopting it seems very in line with the Bullet Train approach.

This article should be a useful resource https://evilmartians.com/chronicles/system-of-a-test-setting-up-end-to-end-rails-testing

Also here's some docs on getting it working with magic_test https://github-wiki-see.page/m/bullet-train-co/magic_test/wiki/Magic-Test-and-Cuprite

**Comment by andrewculver** [comment]
@existentialmutt Sounds great. Want to take a stab at it?

**Comment by existentialmutt** [comment]
Just seeing this now.  I did hit an issue there and solved it with `page.driver.browser.keyboard.type`

**Comment by adampal** [comment]
@existentialmutt that looks good to me if you were able to get around the `send_keys` issue. Without that, it would have been really difficult!

**Comment by gazayas** [comment]
It may not be too big of an issue, but I'm noticing that system tests are failing intermittently in the `System Tests with Cuprite` check.
```
Error:
AuthenticationSystemTest#test_visitors_can_sign-up,_sign-out,_sign-in,_reset_passwords,_etc._with_subscriptions_disabled_on_a_macbook_pro_15_inch:
Ferrum::PendingConnectionsError: Request to http://localhost:3001/ reached server, but there are still pending connections: https://rsms.me/inter/font-files/Inter-roman.var.woff2?v=3.19
    test/system/authentication_test.rb:10:in `block (2 levels) in <class:AuthenticationSystemTest>'
```

Example CircleCI jobs:
[Job 3078](https://app.circleci.com/pipelines/github/bullet-train-co/bullet_train/778/workflows/01eae59c-8fb9-47c0-9c1f-8d431877f21a/jobs/3078)
[Job 2934](https://app.circleci.com/pipelines/github/bullet-train-co/bullet_train/752/workflows/56a1bdd0-1078-45d5-856c-1818d974edb5/jobs/2934)
[Job 2907](https://app.circleci.com/pipelines/github/bullet-train-co/bullet_train/746/workflows/e61f57d2-f1e6-435e-81af-4405c14f15c3/jobs/2907)

Most tests seem to pass just fine if you re-run the jobs in CircleCI, which is what I've been doing with the depfu dependencies.

The issue was addressed [here](https://github.com/rubycdp/ferrum/issues/122) in the Ferrum repository, and other people are seeming to have problems with it when using it with Capybara specfically. The lead contributor [commented](https://github.com/rubycdp/ferrum/issues/122#issuecomment-781223983), and these are the first 3 options that were provided:
> 1. If request is to your local server figure out why it's so slow
> 2. If request is to external server try to block such if it's not vital part of your app
> 3. Try to increase :timeout, because if timeout is reached and there are still pending connection the error is raised.

Since we're not making requests to a local server and we depend on the external server in the system tests, we might just want to increase the timeout value a little bit to see if this takes care of the problem.

**Comment by jagthedrummer** [comment]
[This PR](https://github.com/bullet-train-co/bullet_train/pull/1771) is my 3rd distinct attempt to get cuprite working. It seems _mostly_ stable locally (but not entirely) and on CI (GitHub actions) there are tons of random failures (deets in that PR).

I don't think it's worth spending more time on this, so I'm going to close this issue. If anybody wants to take a stab at getting it working and can submit a PR with whatever needs to be done I'd be more than happy to take a look and help get it landed.
