### ISSUE TITLE
Add system tests for Action Models.

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train#492]
You can see an example of how we set up and then perform a system test for Super Scaffolding in the following three files:

- CI Config: https://github.com/bullet-train-co/bullet_train/blob/main/.circleci/config.yml#L134
- Setup: https://github.com/bullet-train-co/bullet_train/blob/main/test/bin/setup-super-scaffolding-system-test
- Test: https://github.com/bullet-train-co/bullet_train/blob/main/test/system/super_scaffolding_test.rb

We need to do the same thing for each of the Action Model scaffolders, confirming that when `bullet_train-action_models` is installed, you can generate each of the different types of actions and they function in the application as expected.

We should run this on CI as a separate task from the Super Scaffolding tests. However, we should probably group them together in a single CI task similar to how all the Super Scaffolding tests are together in a single task.

The reason we add these tests in this repository is so folks building with Bullet Train can confirm that nothing they've done in their local applications has broken the ability to generate and execute actions.

**Comment by gazayas** [comment]
What I'm envisioning:
```
> bundle exec test/bin/setup-action-models-system-test
> rails test test/system/action_models_test.rb
```

All of the separate actions would be covered in this one file so we can group them together into a single CI task like you mentioned.

I plan on solving this one before the new API support issue so we can have tests in place for it, but if that issue is more important than this one I'll switch back to it and take care of it first.
