### ISSUE TITLE
Mailer doesn't work on Render?

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train#509]
Context at https://discord.com/channels/836637622432170028/836637623048601633/1040374077052956763 .

**Comment by gazayas** [comment]
## Missing assets
I was able to duplicate this issue, and editing the build command <b>for the worker</b> to the following removed the `application.css` error:
```
bundle install && bundle exec rake assets:precompile
```

I got the idea from [this article](https://dev.to/ayushn21/deploy-rails-and-sidekiq-to-rendercom-using-yaml-346) about deploying to Render with Sidekiq and Redis.

## Not starting the Sidekiq Worker
If you look at the article, you can see that they're setting the `startCommand` and `buildCommand` for the worker as well as the web service, which would probably be best for us to do as well. I'm still not entirely sure what the setup should look like, so I'm currently working through that.

When you deploy a new app with the setup we currently have and look at the worker's start command, it looks like what we have in Procfile.dev:
```
bundle exec sidekiq -t 25
```

However we should probably be setting the `REDIS_URL` in the start command. Because our start command is `bundle exec sidekiq -t 25`, it looks like worker won't perform any jobs because it's not connecting to the instance in the first place. I'm trying to get the worker going with the following:
```
REDIS_URL="redis://render-redis-url:6379" bundle exec sidekiq -e production
```

I also had to add `BASE_URL` explicitly in the worker's environment variable.

If I can manage to get the worker going, I'll try to update our `render.yaml` to automate the build and start commands.

**Comment by gazayas** [comment]
@brennanlawrence, could try updating your worker's build command to the following and letting us know what your logs are outputting?
```
bundle install && bundle exec rake assets:precompile
```

I'm afraid we have connected the web service to the Redis instance, so I plan on looking into it more soon.

**Comment by gazayas** [comment]
[Render docs for deploying a Sidekiq worker](https://render.com/docs/deploy-sidekiq-worker) for reference.

**Comment by brennanlawrence** [comment]
@gazayas I added precompile to the worker build command. That seems to have worked, it is no longer throwing the `application.css` error. That being said, the email is missing some styles. 

<img width="768" alt="image" src="https://user-images.githubusercontent.com/65191575/201687413-4e3a0990-79e7-4c2a-8f69-14ee170e808d.png">

As opposed to: 

<img width="790" alt="image" src="https://user-images.githubusercontent.com/65191575/201687642-4a1ab4bc-3814-4fe3-935b-8dc42537f381.png">

I haven't yet tried the sidekiq Start command stuff. I will try that and see what happens.

**Comment by gazayas** [comment]
As far as the production mailer styles styles, I'm currently not 100% sure why they're not all there, but I'll post again if I find anything.

As far as the `REDIS_URL`, if your mail is being sent by the worker you shouldn't have to add the url to anything else! By the way, would you mind sharing your build/start commands for the web service and worker? It'll be easier to debug if other developers run into the same issue in the future.

**Comment by brennanlawrence** [comment]
Sure thing. 

**Web**
Build: `./bin/render-build.sh`
Start: `bundle exec puma -C config/puma.rb`

**Worker**
_It was this:_
Build: `bundle install`
Start: `bundle exec sidekiq -t 25`
_It is currently:_
Build: `bundle install && bundle exec rake assets:precompile`
Start: `bundle exec sidekiq -t 25` (I had changed it to `bundle exec sidekiq -e production` but as far as I could tell it was the same. Though, I could be missing something)

**Comment by gazayas** [comment]
Thank you 🙏

**Comment by gazayas** [comment]
@brennanlawrence It looks like Render updated how Redis instances are created and then deployed with Rails websites. From [the new docs](https://render.com/docs/redis#setting-up-your-redis)
> Previously, Redis had to be deployed as [a private service on Render](https://render.com/docs/deploy-redis). Today, you can create managed Redis instances, which makes it easy to use Redis in a secure, reliable, and completely hands-off way.

When we initially implemented the Render blueprint, Redis instances were private and looked pretty different. I'm still working through the logistics of what that looks like for the Bullet Train starter repository, but you might want to look through [the docs here](https://render.com/docs/deploy-rails-sidekiq) to edit your build command or whatever else might be necessary for your specific use-case.

For example, you can see in the new docs that the build command is now this:
```
buildCommand: bundle install; bundle exec rake assets:precompile; bundle exec rake assets:clean;
```

Again I'll have to keep sifting through the docs myself, but since things were updated on Render's side we'll definitely have to update our blueprint.
