### ISSUE TITLE
Getting duplicate list of items after upgrade, in super-scaffolding created with older version

### ISSUE THREAD

**Issue by flozano** [bullet-train-co/bullet_train#550]
I initally created my project against ea73c67b89dba69697dadb6c9707ede0dad81a7b

I have several models super-scaffolded for CRUD screens, which were working properly.

Today I updated to 878f218f2032efa82f79a03c10c18905d987a969, and all the old scaffolded list views are appearing twice.

**Comment by flozano** [comment]
Reproduced here: https://github.com/flozano/btplayground2

**Comment by flozano** [comment]
My observations:

 - only one `<!-- BEGIN app/views/account/items/_index.html.erb -->` and `<!-- END app/views/account/items/_index.html.erb -->` appear in the rendered html
 - everything inside these two comment tags is duplicate. First element after the BEGIN mentioned is `<updates-for identifier="ImdpZDovL2J0LXBsYXlncm91bmQyL1RlYW0vMTppdGVtcyI=--1e1de8b8ac0de51c2bde915228217edc5464bea304ca46282b5ec1c871b3a26c">`, which appears twice

**Comment by flozano** [comment]
if I remove `<%= action_model_select_controller do %>` ... `<% end %>` wrapping the `updates_for`, the duplication is gone

**Comment by flozano** [comment]
I think I found the reason, after looking at similar issues in other rails projects.

In `_index.html.erb` of the generated scaffolds, views generated with the previous version contained:
```erb
<%= action_model_select_controller do %>
  <%= updates_for context, collection do %>
```

whereas views generated with the newer version are like:
```erb
<%= action_model_select_controller do %>
  <% updates_for context, collection do %>
```

if I change `  <%= ` to `  <% ` in the new ones, the duplication is gone.

**Comment by gazayas** [comment]
Definitely related to https://github.com/bullet-train-co/bullet_train-super_scaffolding/pull/86, the equals sign was deleted so the partial isn't rendered twice, but that definitely complicates things for developers who switch to the newest version of `bullet_train-super_scaffolding` since we don't have a fallback. I'll try to think of a fallback in the meantime and open a PR if I find a good solution.

**Comment by flozano** [comment]
I think the fix is easy enough that breaking compatibility is not so bad this time, but it would be nice to have a doc explaining the bumps in the road that can happen between upgrades and how to fix them.

**Comment by andrewculver** [comment]
@gazayas If this is a fix going forward, I'm OK just having a note for folks that tells them to globally replace `<%= updates for` with `<% updates_for`... is that the fix?

**Comment by andrewculver** [comment]
We used to have a `CHANGELOG.md` for this very purpose. Happy to add one again starting with this.

**Comment by gazayas** [comment]
@andrewculver I think this may be a Nice Partials bug.

The following works just fine:
```erb
# Define foo as a helper method
def foo
  yield
end

# Write the following in a view
<%= foo do %>
  <%= "Test Text" %>
<% end %>
```

However, when we call `yield` via `foo` like this on a nice partial, it gets duplicated:
```erb
<%= foo do %>
  <%= render 'account/shared/box' do |p| %>
    <%= p.content_for :title, "Test Text" %>
  <% end %>
<% end %>
```

I'm not familiar enough with the code base to say exactly what it is, but I noticed there is a lot of content in regards to `yield` so my guess is the bug is there.

## A temporary fix

I was able to simply `capture` the content and render it without duplicating it:
```ruby
def render_with_action_model_check(content)
  if action_models_enabled?
    action_model_select_controller do
      content
    end
  else
    content
  end
end
```

In the view:
```erb
<% content = capture do %>
  <%= updates_for context, collection do %>
  ...
  <% end %>
<% end %>

<%= render_with_action_model_check(content) %>
```

I have [a branch here](https://github.com/bullet-train-co/bullet_train-core/tree/fixes/updates_for) in case you want to check it out.

@kaspth, I know you've worked with Nice Partials too so I'm pinging you just in case.

**Comment by gazayas** [comment]
I get duplicate content on a vanilla rails app as well with the following, so it could just be the fact that we're calling `render` inside this `foo` block which also calls `yield`:

```ruby
# In a helper
def foo
  yield
end
```

```erb
# In a view
<%= foo do %>
  <%= render "bar" do %>
    Duplicated content
  <% end %>
<% end %>
```

```erb
# In the `_bar.html.erb` partial
<%= yield %>
```

**Comment by andrewculver** [comment]
@flozano Finally had an opportunity to look at this properly! Thank you for such a detailed and complete bug report. I'm just going to revert the original change that introduced this issue.

**Comment by andrewculver** [comment]
Actually, @kaspth explained to me what was going on here. Going to fix it properly! 🙏🏻

**Comment by andrewculver** [comment]
This should be fixed now.
