### ISSUE TITLE
Failing tests in new project

### ISSUE THREAD

**Issue by phortx** [bullet-train-co/bullet_train#573]
There are a lot of tests, that fail after generating a new project. Example:

```
Error:
Api::V1::Platform::AccessTokensControllerTest#test_index:
NameError: uninitialized constant Api::V1::Platform::AccessToken

          access_token = Platform::AccessToken.find(access_token_data["id"])
                                 ^^^^^^^^^^^^^
    test/controllers/api/v1/platform/access_tokens_controller_test.rb:26:in `assert_proper_object_serialization'
    test/controllers/api/v1/platform/access_tokens_controller_test.rb:49:in `block in <class:AccessTokensControllerTest>'
```

Or:

```
rails test test/controllers/account/scaffolding/absolutely_abstract/creative_concepts/collaborators_controller_test.rb:27

E

Error:
Account::Scaffolding::AbsolutelyAbstract::CreativeConcepts::CollaboratorsControllerTest#test_should_update_collaborator:
NoMethodError: undefined method `account_scaffolding_absolutely_abstract_creative_concepts_collaborator_url' for #<Account::Scaffolding::AbsolutelyAbstract::CreativeConcepts::CollaboratorsControllerTest:0x000000010d497628>
    test/controllers/account/scaffolding/absolutely_abstract/creative_concepts/collaborators_controller_test.rb:57:in `block in <class:CollaboratorsControllerTest>'
```

**Comment by gazayas** [comment]
Hey @phortx, could you provide the steps you took to generate a new project? I got tests passing with the following steps:

```
> git clone git@github.com:bullet-train-co/bullet_train.git foo
> cd foo
> bin/configure
> bin/setup
```

**Comment by siaw23** [comment]
Can confirm tests pass fine but only if I add the missing step from the README `bin/setup`.

**Comment by gazayas** [comment]
Yes, we prompt the developer to run `bin/setup` here when running `bin/configure`:

https://github.com/bullet-train-co/bullet_train/blob/bcd7ad6dbc81cae84f59f725e6b04a2e9b2868e5/bin/configure#L212

**Comment by siaw23** [comment]
I didn't get to that point because for some reason the `bin/configure` was failing for me so there's no way to know I have to do `bin/setup`, I sent a PR to add it to the README. Maybe we can change "Next you can run `bin/setup` and then `bin/dev`." to "Next you can run `bin/setup` and then `bin/dev`. if you haven't done so already." because without waiting for `bin/configure` and running `bin/setup` right after `bin/configure` things work fine because I have almost everything the `bin/configure` wants to install already. I reckon it might be the same for others.
