### ISSUE TITLE
bin/configure fails on incorrect versions of ruby and node.

### ISSUE THREAD

**Issue by pdebruic** [bullet-train-co/bullet_train#6]
On macos, I'm using the default versions of ruby and node installed by homebrew.

```
~/src/rails/bullet_train % bin/configure
Bullet Train requires Ruby 3.1.1 and `ruby -v` returns ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [arm64-darwin21].
Bullet Train requires Node.js 16.14.0 and `node -v` returns v17.8.0.
~/src/rails/bullet_train % which ruby
/opt/homebrew/opt/ruby/bin/ruby
~/src/rails/bullet_train % which node
/opt/homebrew/bin/node

```

Do I really need to change them for this project?

**Comment by andrewculver** [comment]
@pdebruic So that Ruby check is passing (and should have been printed in green), but yes, we are including a specific Ruby version in `.ruby-version` and Node version in `.nvmrc`, and that's what `bin/configure` is comparing against. You're welcome to try and bump the version in `.nvmrc` to whatever you have installed so the check passes, and let us know if the test suite still passes?

**Comment by andrewculver** [comment]
It's possible going forward that we'll want to not lock in a specific version of either of these things... but we've done this historically and haven't ever heard any concerns about it.

**Comment by alterisian** [comment]
With rbenv I degraded the version in .ruby-version to 3.0 and followed the node update in:
https://phoenixnap.com/kb/update-node-js-version

**Comment by whitemerry** [comment]
Maybe it would be enough to check if current ruby version starts with same as `.ruby-version` instead of 1:1 check - as `rvm` installed version contains suffix but is basically the same one `3.1.1` - `3.1.1p18`?

**Comment by gazayas** [comment]
@whitemerry 
https://github.com/bullet-train-co/bullet_train/blob/bb82b10a996c8a76477e423894c6c798f3e5c8c8/bin/configure#L56
Since we're using `include?` here, I think as long as the string has `3.1.1` we <i>should</i> be okay (my Ruby version returns `3.1.1p18` too). It should pass as long as the node version is updated as well. What string is rvm giving you?

**Comment by andrewculver** [comment]
Should be fixed by https://github.com/bullet-train-co/bullet_train/commit/4d16bfef5a99739e39160631d998aae626891416. 🤞 Now we allow users to skip the enforcement of this.
