### ISSUE TITLE
duplicate lines generated in roles.yml

### ISSUE THREAD

**Issue by ChristopherHelgeson** [bullet-train-co/bullet_train#623]
Where are these duplicate lines coming from? Are the intentional?
ex: 
![image](https://user-images.githubusercontent.com/29275279/213552255-9289be0e-15d3-476e-98b1-2764d0de2b37.png)

**Comment by andrewculver** [comment]
@gazayas I wonder whether these happen if someone runs the scaffolder more than once for the same model?

**Comment by gazayas** [comment]
Seems very likely, I'll try some scaffolding commands and see what I can find

**Comment by gazayas** [comment]
## Duplicate lines
@andrewculver I confirmed that the lines are duplicated when running the command twice:

```
rails g model Project team:references name:string && \
bin/super-scaffold crud Project Team name:text_field --sidebar="ti.ti-world" && \
bin/super-scaffold crud Project Team name:text_field --sidebar="ti.ti-world"
```

It looks like the same thing is happening with Action Models:
```
bin/super-scaffold action-model:targets-many Archive Project Team && \
bin/super-scaffold action-model:targets-many Archive Project Team
```

## Prevent from Super Scaffolding twice
My initial thought is to have a check in place when running the scaffolder to prevent developers from running it twice, especially because Rails does this with models:
```
> rails g model Project team:references name:string
      invoke  active_record
The name 'Project' is either already used in your application or reserved by Ruby on Rails. Please choose an alternative or use --skip-collision-check or --force to skip this check and run this generator again.
```

Maybe we can check if directories/files under the model name have already been created. `crud-field` would have to be handled differently though.

## `add_ability_line_to_roles_yml`:
https://github.com/bullet-train-co/bullet_train-core/blob/fab77efab57126c083e0041f97c0e716560a2ffe/bullet_train-super_scaffolding/lib/scaffolding/transformer.rb#L485-L492

This method is overridden in Action Models Transformer, although I think we can refactor it to just call the original method from `Scaffolding::Transformer`, so I'll try to keep both methods in mind when fixing this.
