### ISSUE TITLE
Does ToDesktop support require their "runtime" to be added?

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train#63]
See https://bullettrain.co/docs/desktop and https://discord.com/channels/836637622432170028/836637623048601633/964569860745093160 for context.

**Comment by gazayas** [comment]
Linking [the docs](https://www.npmjs.com/package/@todesktop/runtime) here for reference.

**Comment by gazayas** [comment]
`runtime` doesn't seem to be <i>required</i> for ToDesktop to function, but it's one of the steps in the setup process, and seems to offer a lot of information that developers will want when releasing a desktop app (auto-updating, crash reports, etc.)

The main problem I'm running into is with esbuild. Running `bin/dev` will yield this error inside a bunch of the packages, and trying to add `--platform=node` doesn't quite fix it:
```
|   The package "fs" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
| 
| ✘ [ERROR] Could not resolve "stream"
| 
|     node_modules/electron-updater/out/differentialDownloader/DataSplitter.js:6:25:
|       6 │ const stream_1 = require("stream");
|         ╵                          ~~~~~~~~
```

Other people are having a similar issue, and I haven't quite found a fix yet, but it's something I think we'll want to look out for if we want to keep supporting desktop app development.
Related issues:
[Why esbuild seems bundling for node instead of browser?](https://github.com/evanw/esbuild/issues/1162)
[The package "util" wasn't found on the file system](https://github.com/evanw/esbuild/issues/1996)

## Running the initialization script
As far as the script itself, my initial thought is to put it in `app/javascript/application.js`, or put it in its own file and call import it to `app/javascript/application.js`. This might also simply be a syntax issue—I think we'll have to use `import` as opposed to `require` for this script. I tried doing so, but couldn't quite get things to work. Here's the original script for reference:
```javascript
const { app, BrowserWindow } = require("electron");
const todesktop = require("@todesktop/runtime");

todesktop.init();

function createWindow() {
  // Create the browser window.
  let win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true
    }
  });

  // and load the index.html of the app.
  win.loadFile("index.html");
}

app.whenReady().then(createWindow);
```

I sent ToDesktop an email, so if I hear from them I'll let you know and I'll look into the issue again.

**Comment by gazayas** [comment]
Hello @davej, I’m glad you found us! From my understanding, we set things up so developers need only one repo, and then they can deploy both a website and a desktop app from that repo. Does that answer your question? If anything, I’m sure @andrewculver could give you a clearer answer.

**Comment by andrewculver** [comment]
@davej Hey Dave, thanks for the clarification! Our guidance to people is to use the product on your homepage, so I think we're good to go here!
